name: Preview

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.event.issue.number || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-comment:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check if the comment was a command, and react with 👀 if it was
        if: github.event.issue.pull_request
        uses: famly/pull-request-comment-trigger@master
        id: check
        with:
          trigger: "/preview"
          reaction: eyes
          prefix_only: true
        env:
          GITHUB_TOKEN: "${{ secrets.CI_GITHUB_TOKEN }}"

      - name: Add info about starting new preview
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.check.outputs.triggered == 'true'
        with:
          recreate: true
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            **🖼️ Preview Environment:** _Starting..._

      - name: Extract current commit
        if: steps.check.outputs.triggered == 'true'
        id: sha
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { owner, repo, number: pull_number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });
            return pr.data.head.sha
      - uses: actions/checkout@v3
        if: steps.check.outputs.triggered == 'true'
        with:
          ref: ${{ steps.sha.outputs.result }}

      - uses: actions/setup-node@v3
        if: steps.check.outputs.triggered == 'true'
        with:
          node-version: 16

      - name: Start frontend tunnel
        id: expose-tunnel
        if: steps.check.outputs.triggered == 'true'
        uses: codetalkio/expose-tunnel@v1.4.0
        with:
          service: localhost.run
          port: 3000
      - name: Fix tunnel url
        id: tunnel-url
        if: steps.check.outputs.triggered == 'true'
        run: |
          url=${{ steps.expose-tunnel.outputs.tunnel-url }}
          fixedUrl=${url::-6}
          echo "tunnel-url=${fixedUrl}" >> $GITHUB_OUTPUT

      - name: Hide preview comment
        if: steps.check.outputs.triggered == 'true'
        uses: actions/github-script@v6
        with:
          result-encoding: string
          github-token: ${{ secrets.CI_GITHUB_TOKEN }}
          script: |
            const { node_id } = context.payload.comment; 

            const query = `
              mutation minimizeComment($id: ID!) {
                minimizeComment(input: { classifier: OUTDATED, subjectId: $id }) {
                  clientMutationId
                }
              }
            `;

            await github.graphql(query, { id: node_id });

      - name: Add info about dependency install
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.expose-tunnel.outputs.tunnel-url != ''
        with:
          recreate: true
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            **🖼️ Preview Environment:** _Installing dependencies..._
      - name: Install dependencies
        if: steps.expose-tunnel.outputs.tunnel-url != ''
        uses: bahmutov/npm-install@v1
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Add info about build
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.expose-tunnel.outputs.tunnel-url != ''
        with:
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          recreate: true
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            **🖼️ Preview Environment:** _Building..._
      - name: Build frontend
        if: steps.expose-tunnel.outputs.tunnel-url != ''
        run: |
          touch .env
          echo NEXTAUTH_URL=${{ steps.tunnel-url.outputs.tunnel-url }} >> .env
          echo NEXTAUTH_SECRET=secret >> .env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> .env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
          echo DATABASE_URL="postgres://postgres:postgres@localhost:5432/postgres" >> .env
          echo SMTP_HOST="host" >> .env
          echo SMTP_USERNAME="username" >> .env
          echo SMTP_PASSWORD="password" >> .env
          echo EMAIL_FROM="emailfrom" >> .env
          npm run build
          npm run db:push
          npm run db:seed

      - name: Starting app
        if: steps.expose-tunnel.outputs.tunnel-url != ''
        run: npm start &

      # Post a comment on the Pull Request with the URL to the tunnel.
      - name: Comment PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: steps.expose-tunnel.outputs.tunnel-url != ''
        with:
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          recreate: true
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            **🖼️ Preview Environment:** ${{ steps.tunnel-url.outputs.tunnel-url }}

              You can stop the preview by clicking "Cancel" on the [GitHub Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      # Keep the CI job alive for 30 minutes before we time out.
      - name: Wait for 30 minutes before timing out (unless overwritten)
        if: steps.expose-tunnel.outputs.tunnel-url != ''
        run: |
          echo "Tunnel URL is ${{ steps.tunnel-url.outputs.tunnel-url }}"
          timeout 31m sleep 7200
          # Gracefully exit if the timeout hits.
          exit 0

      - name: Close comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ failure() || cancelled() }}
        with:
          recreate: true
          number: ${{ github.event.issue.number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          message: |
            🖼️ Preview Environment is **not** running. To start it again, comment `/preview` on this PR.
